config/routes.rb
Rails.application.routes.draw do
  get 'myhistory/index'
  get 'myhistory/points_leaderboard'
  root to: 'home#index'
  get '/home/adminDash' => "home#adminDash", :as => :admin_root
    devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', sessions: "users/sessions" }
    devise_scope :user do
      get 'users/edit', to: 'users/sessions#edit', as: :edit_user_session
      post 'users/edit', to: 'users/sessions#update'
      get 'users/sign_in', to: 'users/sessions#new', as: :new_user_session
      get 'users/sign_out', to: 'users/sessions#destroy', as: :destroy_user_session
  end

  resources :home
  resources :poin_events
  resources :referrals
  resources :events
  resources :event_hists
  resources :users
  resources :sessions
  resources :signups #plural???
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/event_hist.rb
class EventHist < ApplicationRecord
  validates :event_id, presence: true
  validates :user_id, presence: true
  validates :sign_in, presence: true
  validates :point_recv, presence: true
end

app/controllers/event_hists_controller.rb
class EventHistsController < ApplicationController
  before_action :set_event_hist, only: %i[show edit update destroy]

  # GET /event_hists or /event_hists.json
  def index
    @event_hists = EventHist.all
  end

  # GET /event_hists/1 or /event_hists/1.json
  def show; end

  # GET /event_hists/new
  def new
    @event_hist = EventHist.new
  end

  # GET /event_hists/1/edit
  def edit; end

  # POST /event_hists or /event_hists.json
  def create
    @event_hist = EventHist.new(event_hist_params)

    respond_to do |format|
      if @event_hist.save
        format.html { redirect_to event_hist_url(@event_hist), notice: 'Event hist was successfully created.' }
        format.json { render :show, status: :created, location: @event_hist }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event_hist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /event_hists/1 or /event_hists/1.json
  def update
    respond_to do |format|
      if @event_hist.update(event_hist_params)
        format.html { redirect_to event_hist_url(@event_hist), notice: 'Event hist was successfully updated.' }
        format.json { render :show, status: :ok, location: @event_hist }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event_hist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /event_hists/1 or /event_hists/1.json
  def destroy
    @event_hist.destroy

    respond_to do |format|
      format.html { redirect_to event_hists_url, notice: 'Event hist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_event_hist
    @event_hist = EventHist.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def event_hist_params
    params.require(:event_hist).permit(:event_id, :user_id, :sign_in, :point_recv)
  end
end

app/helpers/event_hists_helper.rb
module EventHistsHelper
end

app/views/event_hists/_form.html.erb
<%= form_with(model: event_hist) do |form| %>
  <% if event_hist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event_hist.errors.count, "error") %> prohibited this event_hist from being saved:</h2>

      <ul>
        <% event_hist.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :event_id %>
    <%= form.number_field :event_id %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :sign_in %>
    <%= form.check_box :sign_in %>
  </div>

  <div class="field">
    <%= form.label :point_recv %>
    <%= form.number_field :point_recv %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/event_hists/edit.html.erb
<h1>Editing Event Hist</h1>

<%= render 'form', event_hist: @event_hist %>

<%= link_to 'Show', @event_hist %> |
<%= link_to 'Back', event_hists_path %>

app/views/event_hists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Event Hists</h1>
<br>
Welcome to the Event History index. This page is to record user event attendance. To report a user's attendence, click on "Record User Attendance". To see the event's details, click show. To move around the website, and to edit it click edit. click "Navigation"
<br>
<br>
<table>
  <thead>
    <tr>
      <th>Event</th>
      <th>User</th>
      <th>Sign in</th>
      <th>Point recv</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @event_hists.each do |event_hist| %>
      <tr>
        <td><%= event_hist.event_id %></td>
        <td><%= event_hist.user_id %></td>
        <td><%= event_hist.sign_in %></td>
        <td><%= event_hist.point_recv %></td>
        <td><%= link_to 'Show', event_hist %></td>
        <td><%= link_to 'Edit', edit_event_hist_path(event_hist) %></td>
        <td><%= link_to 'Destroy', event_hist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Record User Attendance', new_event_hist_path %>
<br>
<%= link_to 'My History', myhistory_index_path %>
<br>
<%= link_to 'Navigation', home_index_path %>

app/views/event_hists/new.html.erb
<div class="container">
    <h1>New Event Hist</h1>

    <%= render 'form', event_hist: @event_hist %>
<div>

app/views/event_hists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Event:</strong>
  <%= @event_hist.event_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @event_hist.user_id %>
</p>

<p>
  <strong>Sign in:</strong>
  <%= @event_hist.sign_in %>
</p>

<p>
  <strong>Point recv:</strong>
  <%= @event_hist.point_recv %>
</p>

<%= link_to 'Edit', edit_event_hist_path(@event_hist) %> |
<%= link_to 'Back', event_hists_path %>