config/routes.rb
Rails.application.routes.draw do
  get 'myhistory/index'
  get 'myhistory/points_leaderboard'
  root to: 'home#index'
  get '/home/adminDash' => "home#adminDash", :as => :admin_root
    devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', sessions: "users/sessions" }
    devise_scope :user do
      get 'users/edit', to: 'users/sessions#edit', as: :edit_user_session
      post 'users/edit', to: 'users/sessions#update'
      get 'users/sign_in', to: 'users/sessions#new', as: :new_user_session
      get 'users/sign_out', to: 'users/sessions#destroy', as: :destroy_user_session
  end

  resources :home
  resources :poin_events
  resources :referrals
  resources :events
  resources :event_hists
  resources :users
  resources :sessions
  resources :signups #plural???
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_adminHeader.html.erb
<%= stylesheet_link_tag "header.css" %>

<nav class="navbar navbar-expand-lg navbar-light bg-light" style="font-size:28px;">
  <div class="container-fluid">
    <%= link_to image_tag("logo.png", :size => "80x80" ), admin_root_path, class:"nav-link"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav ms-auto">
        <%= link_to "Home", event_hists_path, class:"nav-link" %>
        <%= link_to "Approval List", event_hists_path, class:"nav-link" %>
        <%= link_to "Events", events_path, class:"nav-link" %>
        <%= link_to "Award Points", poin_events_path, class:"nav-link" %>
        <%= link_to "Announcements", referrals_path, class:"nav-link" %>
        <div class="dropdown">
          <div id="imageDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag(current_user.avatar_url, :size => "80x80" ) %>
          </div>
          <ul class="dropdown-menu" role="menu" aria-labelledby="imageDropdown">
            <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Menu item 1</a></li>
            <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Menu item 2</a></li>
            <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Menu item 3</a></li>
            <li role="presentation" class="divider"></li>
            <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Menu item 4</a></li>
          </ul>
        </div>
        
        <%= link_to "Sign Out", destroy_user_session_path, class:"nav-link" %>
      </div>
    </div>
  </div>
</nav>

app/views/home/_header.html.erb
<%= stylesheet_link_tag "header.css" %>

<nav class="navbar navbar-expand-lg navbar-light bg-light"style="font-size:28px;">
  <div class="container-fluid">
    <%= link_to image_tag("logo.png", :size => "80x80" ), root_path, class:"navbar-brand"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav ms-auto">
        <%= link_to "Event History", event_hists_path, class:"nav-link" %>
        <%= link_to "Events", events_path, class:"nav-link" %>
        <%= link_to "Point Events", poin_events_path, class:"nav-link" %>
        <%= link_to "Referrals", referrals_path, class:"nav-link" %>
        <%= image_tag(current_user.avatar_url, :size => "80x80" ) %>
        <%= link_to "Sign Out", destroy_user_session_path, class:"nav-link" %>
      </div>
    </div>
  </div>
</nav>

app/views/home/adminDash.html.erb
<% @title = "LMSA Admin" %>
<%= stylesheet_link_tag "home.css" %>

<div class="text-center" style="color:red;">
    <h1>Welcome to LMSA+</h1>
    <h3>Admin Dashboard</h3>

    <p>
        <strong>User Name: </strong>
        <%= current_user.first_name %>
        <%= current_user.last_name %>
    </p>

    <p>
        <strong>User ID: </strong>
        <%= current_user.id %>
    </p>

    <p>
        <strong>User Email: </strong>
        <%= current_user.email %>
    </p>
</div>

app/views/home/index.html.erb
<% @title = "LMSA Home" %>
<%= stylesheet_link_tag "home.css" %>


<div class="container py-4">


    <div class="p-5 mb-4 bg-light rounded-3" style="text-align: center;">
      <div class="container-fluid py-5">
        <h1 class="display-10 fw-bold">Welcome back <%= current_user.first_name %>!</h1>
        <p> <strong>Points: </strong> <%= current_user.sum_points %> </p>
        <p>
            <strong>User Name: </strong>
            <%= current_user.first_name %>
            <%= current_user.last_name %>
        </p>

        <p>
            <strong>User ID: </strong>
            <%= current_user.id %>
        </p>

        <p>
            <strong>User Email: </strong>
            <%= current_user.email %>
        </p>

        <p>
            <strong>User Birthdate: </strong>
            <%= current_user.bod %>
        </p>

        <p>
            <strong>User Bio: </strong>
            <%= current_user.bioConfirmation %>
        </p>

         <% if current_user.major.present? %>
            <p>
                <strong>User Major: </strong>
                <%= current_user.major %>
            </p>
        <% end %>

        <a href="<%=edit_user_session_path%>">
            <button class="btn btn-outline-secondary text-dark" type="button">Edit My Info</button>
        </a>



      </div>
    </div>

    <div class="row align-items-md-stretch">
      <div class="col-md-6">
        <div class="h-100 p-5 text-white bg-dark rounded-3">
          <h2>Change the background</h2>
          <p>Swap the background-color utility and add a `.text-*` color utility to mix up the jumbotron look. Then, mix and match with additional component themes and more.</p>
          <button class="btn btn-outline-light" type="button">Example button</button>
        </div>
      </div>
      <div class="col-md-6">
        <div class="h-100 p-5 bg-light border rounded-3">
          <h2>Add borders</h2>
          <p>Or, keep it light and add a border for some added definition to the boundaries of your content. Be sure to look under the hood at the source HTML here as we've adjusted the alignment and sizing of both column's content for equal-height.</p>
          <button class="btn btn-outline-secondary" type="button">Example button</button>
        </div>
      </div>
    </div>
  </div>

<br>
  
<%= link_to 'Points Leaderboard', myhistory_points_leaderboard_path %>