config/routes.rb
Rails.application.routes.draw do
  get 'myhistory/index'
  get 'myhistory/points_leaderboard'
  root to: 'home#index'
  get '/home/adminDash' => "home#adminDash", :as => :admin_root
    devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', sessions: "users/sessions" }
    devise_scope :user do
      get 'users/edit', to: 'users/sessions#edit', as: :edit_user_session
      post 'users/edit', to: 'users/sessions#update'
      get 'users/sign_in', to: 'users/sessions#new', as: :new_user_session
      get 'users/sign_out', to: 'users/sessions#destroy', as: :destroy_user_session
  end

  resources :home
  resources :poin_events
  resources :referrals
  resources :events
  resources :event_hists
  resources :users
  resources :sessions
  resources :signups #plural???
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :event_hists
  validates :event_id, presence: true
  validates :event_name, presence: true
  validates :event_date, presence: true
  validates :point_val, presence: true
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[show edit update destroy]

  # GET /events or /events.json
  def index
    @events = Event.all
  end

  # GET /events/1 or /events/1.json
  def show; end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit; end

  # POST /events or /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to event_url(@event), notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to event_url(@event), notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = Event.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def event_params
    params.require(:event).permit(:event_id, :event_name, :event_type, :event_date, :description, :event_creator,
                                  :virtual, :password, :meeting_link, :signin_time, :point_val, :graphics, :total_event_hr)
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<div class="container">
<%= form_with(model: event) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">

    <%= form.label :event_id, class: "form-label" %>
    <%= form.text_field :event_id, {class: "form-control", placeholder: "Event ID"} %>

  </div>
  
  <div class="mb-3">

    <%= form.label :event_name, class: "form-label" %>
    <%= form.text_field :event_name, {class: "form-control", placeholder: "Event Name"} %>

  </div>

  <div class="mb-3">

    <%= form.label :event_type, class: "form-label" %>
    <%= form.text_field :event_type, {class: "form-control", placeholder: "Event Type"} %>
    
  </div>

  <div class="mb-3">

    <%= form.label :event_date, class: "form-label" %>
    <%= form.datetime_select :event_date, {class: "form-control", placeholder: "Event Date"} %>

  </div>

  <div class="mb-3">

    <%= form.label :description, class: "form-label" %>
    <%= form.text_field :description, {class: "form-control", placeholder: "Description"} %>

  </div>

  <div class="mb-3 form-check">

    <%= form.label :virtual, class: "form-check-label" %>
    <%= form.check_box :virtual, class: "form-check-input" %>

  </div>

  <div class="mb-3">

    <%= form.label :password, class: "form-label" %>
    <%= form.text_field :password, {class: "form-control", placeholder: "Password"} %>

  </div>

  <div class="mb-3">

    <%= form.label :meeting_link, class: "form-label" %>
    <%= form.text_field :meeting_link, {class: "form-control", placeholder: "Meeting Link"} %>

  </div>

  <div class="mb-3">

    <%= form.label :signin_time, class: "form-label" %>
    <%= form.datetime_select :signin_time, {class: "form-control", placeholder: "Sign In Time"} %>

  </div>

  <div class="mb-3">

    <%= form.label :point_val, class: "form-label" %>
    <%= form.number_field :point_val, {class: "form-control", placeholder: "Value"} %>

  </div>

  <div class="mb-3">

    <%= form.label :graphics, class: "form-label" %>
    <%= form.text_field :graphics, {class: "form-control", placeholder: "Graphics"} %>

  </div>

  <div class="mb-3">

    <%= form.label :total_event_hr, class: "form-label" %>
    <%= form.text_field :total_event_hr, {class: "form-control", placeholder: "Hours"} %>

  </div>

  <%= form.submit "Submit", class:"btn btn-secondary" %>
  
<% end %>
</div>

app/views/events/edit.html.erb
<div class="container">
    <h1>Editing Event</h1>
</div>

<%= render 'form', event: @event %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">

  <% if current_user.admin==true %>
    <%= link_to "New Event", new_event_path, {class: "btn btn-secondary text-light", type: "button"} %>
  <% end %>

  <br>
  <br>
  
  <div id="calendar"></div>

</div> 

app/views/events/new.html.erb
<div class="container">
    <h1>New Event</h1>
</div>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></div>

<div class="container">

  <h1><%= @event.event_name %></h1>

  <div class="d-flex flex-column bd-highlight mb-3">

    <div class="p-2 bd-highlight">
      <strong>Event ID: </strong> 
      <%= @event.event_id %>
    </div>

    <div class="p-2 bd-highlight">
      <strong>Event name:</strong>
      <%= @event.event_name %>
    </div>

    <div class="p-2 bd-highlight">
      <strong>Event type:</strong>
      <%= @event.event_type %>
    </div>

    <div class="p-2 bd-highlight">
      <strong>Event date:</strong>
      <%= @event.event_date %>
    </div>

    <div class="p-2 bd-highlight">
      <strong>Description:</strong>
      <%= @event.description %>
    </div>

    <div class="p-2 bd-highlight">
      <strong>Event creator:</strong>
      <%= @event.event_creator %>
    </div>

    <div class="p-2 bd-highlight">
      <strong>Virtual:</strong>
      <%= @event.virtual %>
    </div>

    <div class="p-2 bd-highlight">
      <strong>Password:</strong>
      <%= @event.password %>
    </div>

    <div class="p-2 bd-highlight">
      <strong>Meeting link:</strong>
      <%= @event.meeting_link %>
    </div>

    <div class="p-2 bd-highlight">
      <strong>Signin time:</strong>
      <%= @event.signin_time %>
    </div>

    <div class="p-2 bd-highlight">
      <strong>Point val:</strong>
      <%= @event.point_val %>
    </div>

    <div class="p-2 bd-highlight">
      <strong>Graphics:</strong>
      <%= @event.graphics %>
    </div>

    <div class="p-2 bd-highlight">
      <strong>Total event hr:</strong>
      <%= @event.total_event_hr %>
    </div>
    
  </div>


  <button type="button" class="btn btn-secondary" data-bs-toggle="modal" data-bs-target="#exampleModal">
    Launch demo modal
  </button>

  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Sign In to <%= @event.event_name %></h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <form>
            <label for="password" class="col-form-label">Password:</label>
            <input type="text" class="form-control" id="password">
          </form>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Sing In</button>
        </div>
      </div>
    </div>
  </div>

<%= link_to 'Edit', edit_event_path(@event), class:"btn btn-secondary text-light" %>
<%= link_to 'Destroy', @event, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-secondary text-light" %>
<%= link_to 'Sign In',  event_hists_path(:event_hist => {:event_id => @event.event_id, :user_id => current_user.id, :sign_in => true, :point_recv => @event.point_val}), method: :post, class:"btn btn-secondary text-light" %>
<%= link_to 'Back', events_path, class:"btn btn-secondary text-light" %>

</div>