config/routes.rb
Rails.application.routes.draw do
  get 'myhistory/index'
  get 'myhistory/points_leaderboard'
  root to: 'home#index'
  get '/home/adminDash' => "home#adminDash", :as => :admin_root
    devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', sessions: "users/sessions" }
    devise_scope :user do
      get 'users/edit', to: 'users/sessions#edit', as: :edit_user_session
      post 'users/edit', to: 'users/sessions#update'
      get 'users/sign_in', to: 'users/sessions#new', as: :new_user_session
      get 'users/sign_out', to: 'users/sessions#destroy', as: :destroy_user_session
  end

  resources :home
  resources :poin_events
  resources :referrals
  resources :events
  resources :event_hists
  resources :users
  resources :sessions
  resources :signups #plural???
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/referral.rb
class Referral < ApplicationRecord
  validates :old_member, presence: true
  validates :email, presence: true
end

app/controllers/referrals_controller.rb
class ReferralsController < ApplicationController
  before_action :set_referral, only: %i[show edit update destroy]

  # GET /referrals or /referrals.json
  def index
    @referrals = Referral.all
  end

  # GET /referrals/1 or /referrals/1.json
  def show; end

  # GET /referrals/new
  def new
    @referral = Referral.new
  end

  # GET /referrals/1/edit
  def edit; end

  # POST /referrals or /referrals.json
  def create
    @referral = Referral.new(referral_params)

    respond_to do |format|
      if @referral.save
        format.html { redirect_to referral_url(@referral), notice: 'Referral was successfully created.' }
        format.json { render :show, status: :created, location: @referral }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @referral.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /referrals/1 or /referrals/1.json
  def update
    respond_to do |format|
      if @referral.update(referral_params)
        format.html { redirect_to referral_url(@referral), notice: 'Referral was successfully updated.' }
        format.json { render :show, status: :ok, location: @referral }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @referral.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /referrals/1 or /referrals/1.json
  def destroy
    @referral.destroy

    respond_to do |format|
      format.html { redirect_to referrals_url, notice: 'Referral was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_referral
    @referral = Referral.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def referral_params
    params.require(:referral).permit(:old_member, :new_member, :guest_first_name, :guest_last_name, :medical_prof,
                                     :email, :date_referred, :admin_approved)
  end
end

app/helpers/referrals_helper.rb
module ReferralsHelper
end

app/views/referrals/_form.html.erb
<%= form_with(model: referral) do |form| %>
  <% if referral.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(referral.errors.count, "error") %> prohibited this referral from being saved:</h2>

      <ul>
        <% referral.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :old_member %>
    <%= form.number_field :old_member %>
  </div>

  <div class="field">
    <%= form.label :new_member %>
    <%= form.number_field :new_member %>
  </div>

  <div class="field">
    <%= form.label :guest_first_name %>
    <%= form.text_field :guest_first_name %>
  </div>

  <div class="field">
    <%= form.label :guest_last_name %>
    <%= form.text_field :guest_last_name %>
  </div>

  <div class="field">
    <%= form.label :medical_prof %>
    <%= form.check_box :medical_prof %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :date_referred %>
    <%= form.datetime_select :date_referred %>
  </div>

  <div class="field">
    <%= form.label :admin_approved %>
    <%= form.text_field :admin_approved %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/referrals/edit.html.erb
<h1>Editing Referral</h1>

<%= render 'form', referral: @referral %>

<%= link_to 'Show', @referral %> |
<%= link_to 'Back', referrals_path %>

app/views/referrals/index.html.erb
<p id="notice"><%= notice %></p>
<br>
Welcome to the Referrals index. This page is to record when a member recruits another member. To report a referral, click on "New Referral". To see a user's details, click show, and to edit it click edit. To move around the website, click "Navigation"
<br>
<br>
<h1>Referrals</h1>

<table>
  <thead>
    <tr>
      <th>Old member</th>
      <th>New member</th>
      <th>Guest first name</th>
      <th>Guest last name</th>
      <th>Medical prof</th>
      <th>Email</th>
      <th>Date referred</th>
      <th>Admin approved</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @referrals.each do |referral| %>
      <tr>
        <td><%= referral.old_member %></td>
        <td><%= referral.new_member %></td>
        <td><%= referral.guest_first_name %></td>
        <td><%= referral.guest_last_name %></td>
        <td><%= referral.medical_prof %></td>
        <td><%= referral.email %></td>
        <td><%= referral.date_referred %></td>
        <td><%= referral.admin_approved %></td>
        <td><%= link_to 'Show', referral %></td>
        <td><%= link_to 'Edit', edit_referral_path(referral) %></td>
        <td><%= link_to 'Destroy', referral, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Referral', new_referral_path %>
<br>
<%= link_to 'Navigation', home_index_path %>

app/views/referrals/new.html.erb
<h1>New Referral</h1>

<%= render 'form', referral: @referral %>

<%= link_to 'Back', referrals_path %>

app/views/referrals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Old member:</strong>
  <%= @referral.old_member %>
</p>

<p>
  <strong>New member:</strong>
  <%= @referral.new_member %>
</p>

<p>
  <strong>Guest first name:</strong>
  <%= @referral.guest_first_name %>
</p>

<p>
  <strong>Guest last name:</strong>
  <%= @referral.guest_last_name %>
</p>

<p>
  <strong>Medical prof:</strong>
  <%= @referral.medical_prof %>
</p>

<p>
  <strong>Email:</strong>
  <%= @referral.email %>
</p>

<p>
  <strong>Date referred:</strong>
  <%= @referral.date_referred %>
</p>

<p>
  <strong>Admin approved:</strong>
  <%= @referral.admin_approved %>
</p>

<%= link_to 'Edit', edit_referral_path(@referral) %> |
<%= link_to 'Back', referrals_path %>